### ISSUE TITLE
Error: microconfig/microconfig/microconfig: Calling bottle :unneeded is disabled! There is no replacement.

### ISSUE THREAD

**Issue by danny-su** [microconfig/homebrew-microconfig#1]
Error: microconfig/microconfig/microconfig: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the microconfig/microconfig tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/microconfig/homebrew-microconfig/Formula/microconfig.rb:5

**Comment by kapodes** [comment]
Thanks for reporting this. I will take a look

**Comment by kapodes** [comment]
@danny-su I updated the manifest so it should work now.

**Comment by danny-su** [comment]
@kapodes Please fix the same issue https://github.com/microconfig/homebrew-microctl/issues/1

**Comment by kapodes** [comment]
closing this as fixed
